//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhcrSpec) DeepCopyInto(out *GhcrSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhcrSpec.
func (in *GhcrSpec) DeepCopy() *GhcrSpec {
	if in == nil {
		return nil
	}
	out := new(GhcrSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpaSpec) DeepCopyInto(out *OpaSpec) {
	*out = *in
	in.GithubToken.DeepCopyInto(&out.GithubToken)
	in.BundlePublicKey.DeepCopyInto(&out.BundlePublicKey)
	if in.Ghcr != nil {
		in, out := &in.Ghcr, &out.Ghcr
		*out = new(GhcrSpec)
		**out = **in
	}
	if in.Pv != nil {
		in, out := &in.Pv, &out.Pv
		*out = new(PvSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpaSpec.
func (in *OpaSpec) DeepCopy() *OpaSpec {
	if in == nil {
		return nil
	}
	out := new(OpaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PvSpec) DeepCopyInto(out *PvSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PvSpec.
func (in *PvSpec) DeepCopy() *PvSpec {
	if in == nil {
		return nil
	}
	out := new(PvSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigList) DeepCopyInto(out *SecurityConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigList.
func (in *SecurityConfigList) DeepCopy() *SecurityConfigList {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigSpec) DeepCopyInto(out *SecurityConfigSpec) {
	*out = *in
	if in.Tokenx != nil {
		in, out := &in.Tokenx, &out.Tokenx
		*out = new(TokenXSpec)
		**out = **in
	}
	if in.Opa != nil {
		in, out := &in.Opa, &out.Opa
		*out = new(OpaSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigSpec.
func (in *SecurityConfigSpec) DeepCopy() *SecurityConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigStatus) DeepCopyInto(out *SecurityConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigStatus.
func (in *SecurityConfigStatus) DeepCopy() *SecurityConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenXSpec) DeepCopyInto(out *TokenXSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenXSpec.
func (in *TokenXSpec) DeepCopy() *TokenXSpec {
	if in == nil {
		return nil
	}
	out := new(TokenXSpec)
	in.DeepCopyInto(out)
	return out
}
