apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    accesserator-webhooks: enabled
    istio.io/rev: default
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: app
  namespace: test
  labels:
    skiperator/security: "enabled"
spec:
  image: nginxinc/nginx-unprivileged:latest
  port: 8080
  replicas: 1
  accessPolicy:
    outbound:
      external:
        - host: ghcr.io
          ports:
            - name: https
              protocol: HTTPS
              port: 443
        - host: pkg-containers.githubusercontent.com
          ports:
            - name: https
              protocol: HTTPS
              port: 443
        - host: objects.githubusercontent.com
          ports:
            - name: https
              protocol: HTTPS
              port: 443
      rules:
        - application: another-app
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: another-app
  namespace: test
  labels:
    skiperator/security: "enabled"
spec:
  image: nginxinc/nginx-unprivileged:latest
  port: 8080
  replicas: 1
  accessPolicy:
    inbound:
      rules:
        - application: app
    outbound:
      external:
        - host: ghcr.io
          ports:
            - name: https
              protocol: HTTPS
              port: 443
        - host: pkg-containers.githubusercontent.com
          ports:
            - name: https
              protocol: HTTPS
              port: 443
        - host: objects.githubusercontent.com
          ports:
            - name: https
              protocol: HTTPS
              port: 443
---
apiVersion: accesserator.kartverket.no/v1alpha
kind: SecurityConfig
metadata:
  name: security-config-app
  namespace: test
spec:
  tokenx:
    enabled: true
  opa:
    enabled: true
    githubCredentials:
      clientTokenKey: "github_token"
      clientTokenRef: "opa-github-secret"
    bundlePublicKey: "sfjnskfjsnkfjsnkjsbg"
    bundleRepo: "ldjfhsdjlf"
    bundleResource: "ghcr.io/kartverket/opa-bundle:latest"
  applicationRef: app
---
apiVersion: accesserator.kartverket.no/v1alpha
kind: SecurityConfig
metadata:
  name: security-config-another-app
  namespace: test
spec:
  tokenx:
    enabled: true
  opa:
    enabled: true
    githubCredentials:
      clientTokenKey: "github_token"
      clientTokenRef: "opa-github-secret"
    bundlePublicKey: "sfjnskfjsnkfjsnkjsbg"
    bundleRepo: "ldjfhsdjlf"
    bundleResource: "ghcr.io/kartverket/opa-bundle:latest"
  applicationRef: another-app
---
apiVersion: ztoperator.kartverket.no/v1alpha1
kind: AuthPolicy
metadata:
  name: authpolicy
  namespace: test
spec:
  enabled: true
  selector:
    matchLabels:
      app: another-app
  wellKnownURI: http://tokendings.obo:7456/.well-known/oauth-authorization-server
  allowedAudiences:
    - value: "kind-accesserator:test:another-app"
  ignoreAuthRules:
    - paths:
        - /open/path