apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    accesserator-webhooks: enabled
    istio.io/rev: default
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: app
  namespace: test
  labels:
    skiperator/security: "enabled"
spec:
  image: nginxinc/nginx-unprivileged:latest
  port: 8080
  replicas: 1
  accessPolicy:
    outbound:
      rules:
        - application: tokendings
          namespace: obo
---
apiVersion: accesserator.kartverket.no/v1alpha
kind: SecurityConfig
metadata:
  name: security-config
  namespace: test
spec:
  tokenx:
    enabled: true
  applicationRef: app
---
apiVersion: nais.io/v1
kind: Jwker
metadata:
  name: app-jwker
  namespace: test
spec:
  accessPolicy:
    inbound:
      rules:
        - application: app-jwker
          namespace: test
          cluster: kind-accesserator
    outbound:
      rules:
        - application: app-jwker
          namespace: test
          cluster: kind-accesserator
  secretName: app-jwker-secret