apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    webhooks: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: app
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
